default/objects/Feed_Event__c/Feed_Event__c.object-meta.xml
<CustomObject>
    <description>A description of an event that took place in relation to a Conversation.</description>
    <label>Feed Event</label>
    <nameField>
        <displayFormat>Feed Event-{0000}</displayFormat>
        <label>Feed Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feed Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Feed_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date and time at which the event occurred.</description>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

default/classes/feedback/builders/FeedEventBuilder.cls
/**
 * Specifies an object that can create feed events. Subclasses must have an
 * empty constructor, to allow dynamic instantiation.
 */
public abstract class FeedEventBuilder {

    public FeedItemModel generate(
            PersonModel actor,
            Feed_Event__c event,
            Id viewerId,
            SObject subject) {
        return addDetails(createBaseEvent(actor, event), viewerId, subject);
    }

    @TestVisible
    private FeedItemModel createBaseEvent(PersonModel actor, Feed_Event__c event) {
        FeedItemModel item = new FeedItemModel();
        item.event = new FeedEventModel();
        item.id = event.Id;
        item.itemDate = DateUtils.datetimeToStringInUserTimeZone(event.Date__c);
        item.event.actor = actor;
        return item;
    }

    /**
     * Adds event-specific details to the item.
     */
    protected abstract FeedItemModel addDetails(
            FeedItemModel item, Id viewerId, SObject subject);
}