default/objects/Feed_Event__c/Feed_Event__c.object-meta.xml
<CustomObject>
    <description>A description of an event that took place in relation to a Conversation.</description>
    <label>Feed Event</label>
    <nameField>
        <displayFormat>Feed Event-{0000}</displayFormat>
        <label>Feed Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feed Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Feed_Event__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <description>The ID of the agent who performed the described action.</description>
    <label>Actor</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Feed_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date and time at which the event occurred.</description>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

default/objects/Feed_Event__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The ID of the subject upon or for whom the action was performed.</description>
    <label>Subject</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Feed_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of action this event describes.</description>
    <label>Type</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/feedback/utils/FeedEventUtils.cls
public class FeedEventUtils {

    /**
     * Creates a Feed Event, with the current viewer as the actor.
     */
    public static Feed_Event__c create(Id subjectId, String eventType) {
        Feed_Event__c event = new Feed_Event__c(
            Actor__c = TeamMemberUtils.getTeamMemberId(UserInfo.getUserId()),
            Date__c = Datetime.now(),
            Subject__c = subjectId,
            Type__c = eventType
        );
        return FeedEventRepository.insertRecord(event);
    }
}