default/objects/Feed_Event__c/Feed_Event__c.object-meta.xml
<CustomObject>
    <description>A description of an event that took place in relation to a Conversation.</description>
    <label>Feed Event</label>
    <nameField>
        <displayFormat>Feed Event-{0000}</displayFormat>
        <label>Feed Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feed Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Feed_Event__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <description>The ID of the agent who performed the described action.</description>
    <label>Actor</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Feed_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date and time at which the event occurred.</description>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

default/objects/Feed_Event__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The ID of the subject upon or for whom the action was performed.</description>
    <label>Subject</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Feed_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of action this event describes.</description>
    <label>Type</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/feedback/utils/FeedEventUtilsTest.cls
@isTest
public class FeedEventUtilsTest {

    @isTest
    private static void testCreate() {

        // GIVEN a subject for an event
        fHCM2__Team_Member__c tm = new TeamMemberTestUtils.TeamMemberBuilder()
                .setUser(UserInfo.getUserId())
                .build();

        // WHEN I create the event
        FeedEventUtils.create(tm.Id, 'TM Created');

        // THEN it has the correct details
        List<Feed_Event__c> events =
                FeedEventRepository.getBySubjects(new Set<Id>{tm.Id});
        System.assertEquals(1, events.size());
        System.assertEquals(tm.Id, events[0].Actor__c);
        System.assertNotEquals(null, events[0].Date__c);
        System.assertEquals(tm.Id, events[0].Subject__c);
        System.assertEquals('TM Created', events[0].Type__c);
    }
}