default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective_Collaborator__c/Objective_Collaborator__c.object-meta.xml
<CustomObject>
    <description>Junction object linking an Objective with a Team Member who is authorised to collaborate on it, as defined by their access type.</description>
    <label>Objective Collaborator</label>
    <nameField>
        <label>Objective Collaborator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Collaborators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Objective_Collaborator__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>The kind of access granted to the collaborator.</description>
    <label>Access Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Objective_Collaborator__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>The Objective on which the Team Member can collaborate.</description>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Objective Collaborators</relationshipLabel>
    <relationshipName>Objective_Collaborators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Objective_Collaborator__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Team Member who is the collaborator.</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objective Collaborators</relationshipLabel>
    <relationshipName>Objective_Collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/objectives/repositories/ObjectiveCollaboratorRepository.cls
public class ObjectiveCollaboratorRepository {

    /**
     * Gets all Collaborator junction objects linking to a given Objective ID.
     */
    public static List<Objective_Collaborator__c> getForObjective(Id objectiveId) {
        return [
            SELECT
                Id,
                Access_Type__c,
                Objective__c,
                Team_Member__c
            FROM Objective_Collaborator__c
            WHERE Objective__c = :objectiveId
        ];
    }

    /**
     * Gets all Collaborator junction objects linking to an Objective ID in the
     * given set.
     */
    public static List<Objective_Collaborator__c> getForObjectives(Set<Id> objectiveIds) {
        return [
            SELECT
                Id,
                Access_Type__c,
                Objective__c,
                Team_Member__c
            FROM Objective_Collaborator__c
            WHERE Objective__c IN :objectiveIds
        ];
    }

    /**
     * Gets all Collaborator junction objects linking to a given Team Member ID.
     */
    public static List<Objective_Collaborator__c> getForTeamMember(Id tmId) {
        return [
            SELECT
                Id,
                Access_Type__c,
                Objective__c,
                Team_Member__c
            FROM Objective_Collaborator__c
            WHERE Team_Member__c = :tmId
        ];
    }
}