default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Objective_Collaborator__c/Objective_Collaborator__c.object-meta.xml
<CustomObject>
    <description>Junction object linking an Objective with a Team Member who is authorised to collaborate on it, as defined by their access type.</description>
    <label>Objective Collaborator</label>
    <nameField>
        <label>Objective Collaborator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Collaborators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Objective_Collaborator__c/fields/Access_Type__c.field-meta.xml
<CustomField>
    <fullName>Access_Type__c</fullName>
    <description>The kind of access granted to the collaborator.</description>
    <label>Access Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Objective_Collaborator__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>The Objective on which the Team Member can collaborate.</description>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Objective Collaborators</relationshipLabel>
    <relationshipName>Objective_Collaborators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Objective_Collaborator__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Team Member who is the collaborator.</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objective Collaborators</relationshipLabel>
    <relationshipName>Objective_Collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/objectives/repositories/ObjectiveCollaboratorRepositoryTest.cls
@isTest
public class ObjectiveCollaboratorRepositoryTest {

    private static Objective__c objective;
    private static Objective_Collaborator__c junction;
    private static fHCM2__Team_Member__c tm;

    private static void setUp() {
        tm = new TeamMemberTestUtils.TeamMemberBuilder().build();

        objective = new Objective__c(
            Title__c = 'Watch Aquila'
        );
        insert objective;

        junction = new Objective_Collaborator__c(
            Objective__c = objective.Id,
            Team_Member__c = tm.Id,
            Access_Type__c = 'Espionager'
        );
        insert junction;
    }

    @isTest
    private static void testGetForObjective() {

        // GIVEN an objective with a collaborator
        setUp();

        // WHEN I get all junction objects pointing to it
        List<Objective_Collaborator__c> junctions =
                ObjectiveCollaboratorRepository.getForObjective(objective.Id);

        // THEN I get one
        System.assertEquals(1, junctions.size());

        // AND it is the right one
        System.assertEquals(junction.Id, junctions[0].Id);
    }

    @isTest
    private static void testGetForObjectives() {

        // GIVEN an objective with a collaborator
        setUp();

        // WHEN I get all junction objects pointing to it as part of a set
        Set<Id> objectiveIds = new Set<Id>{objective.Id};
        List<Objective_Collaborator__c> junctions =
                ObjectiveCollaboratorRepository.getForObjectives(objectiveIds);

        // THEN I get one
        System.assertEquals(1, junctions.size());

        // AND it is the right one
        System.assertEquals(junction.Id, junctions[0].Id);
    }

    @isTest
    private static void testGetForTeamMember() {

        // GIVEN a TM who is a collaborator on an objective
        setUp();

        // WHEN I get all junction objects linking them to objectives
        List<Objective_Collaborator__c> junctions =
                ObjectiveCollaboratorRepository.getForTeamMember(tm.Id);

        // THEN I get one
        System.assertEquals(1, junctions.size());

        // AND it is the right one
        System.assertEquals(junction.Id, junctions[0].Id);
    }
}