default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/objectives/notifications/ObjectiveStatusChangeNotificationTest.cls
@isTest
public class ObjectiveStatusChangeNotificationTest {

    private static fHCM2__Team_Member__c subject;
    private static fHCM2__Team_Member__c viewer;
    private static ObjectiveModel objective;

    private static void setUp() {

        viewer = new TeamMemberTestUtils.TeamMemberBuilder()
                .setUser(UserInfo.getUserId())
                .setName('Wilma Worm')
                .build();

        subject = new TeamMemberTestUtils.TeamMemberBuilder()
                .setManager(viewer.Id)
                .setUser(TeamMemberTestUtils.createUser('Terrence', 'Tenrec').Id)
                .setName('Terrence Tenrec')
                .build();

        objective = new ObjectiveTestUtils.ObjectiveBuilder()
                .setTeamMember(subject.Id)
                .setTitle('Title')
                .setStatus(ObjectiveUtils.STATUS_ACTIVE)
                .save()
                .build();
    }

    @isTest
    private static void testBuildBody() {

        // GIVEN some Objective about a Team Member
        setUp();

        // AND the status has been changed
        Objective__c changedObjective = new Objective__c(
            Id = objective.Id,
            Title__c = objective.title,
            Status__c = ObjectiveUtils.STATUS_CLOSED,
            Team_Member__c = subject.Id
        );
        update changedObjective;
        changedObjective = ObjectiveRepository.get(changedObjective.Id);

        // WHEN I build the body for the Notification about it
        Notification notification = ObjectiveStatusChangeNotification.create(
                ObjectiveModelBuilder.build(changedObjective));

        // THEN it is of the expected format
        System.assert(Pattern.matches(
                '<p>Wilma Worm'
                +  '.?'
                +  'closed'
                +  '.*?'
                +  'Title'
                +  '.*?'
                +  String.valueOf(subject.Id)
                +  '.*?'
                +  String.valueOf(objective.Id),
                notification.body
        ));
    }
}