default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>e.g. Company, Personal, Career</description>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Company_Objective__c.field-meta.xml
<CustomField>
    <fullName>Company_Objective__c</fullName>
    <description></description>
    <label>Company Objective</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Objective was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Objective__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date the objective should be completed by</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <description>Date the objective should be reviewed</description>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <description>Visibility of an objective, e.g. &#39;public&#39;, &#39;team&#39;, &#39;private&#39;.</description>
    <label>Visibility</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/builders/ObjectiveRecordBuilder.cls
/**
 * Builder for producing Objective__c records from ObjectiveModels.
 */
public class ObjectiveRecordBuilder {

    private Objective__c objective;

    public ObjectiveRecordBuilder(ObjectiveModel om) {
        objective = new Objective__c(
            Id = om.id,
            Category__c = om.category,
            Company_Objective__c = om.companyObjective,
            Description__c = om.description,
            End_Date__c = DateUtils.stringToDate(om.endDate),
            Priority__c = om.priority,
            Review_Date__c = DateUtils.stringToDate(om.reviewDate),
            Team_Member__c = om.tmId,
            Title__c = om.title,
            Visibility__c = ObjectiveUtils.VISIBILITY_PRIVATE
        );
    }

    public ObjectiveRecordBuilder setStatus(String status) {
        objective.Status__c = status;
        return this;
    }

    public ObjectiveRecordBuilder save() {

        if (objective.Id == null) {
            // Set the artificial created date (SPPLDEV-5734)
            objective.Created_Date__c = Datetime.now();
        }

        upsert objective;
        objective = ObjectiveRepository.get(objective.Id);
        return this;
    }

    public Objective__c build() {
        return objective;
    }
}