default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>e.g. Company, Personal, Career</description>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>Date on which the objective was closed</description>
    <label>Closed Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Objective__c/fields/Company_Objective__c.field-meta.xml
<CustomField>
    <fullName>Company_Objective__c</fullName>
    <description></description>
    <label>Company Objective</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Objective was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Objective__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date the objective should be completed by</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <description>Date the objective should be reviewed</description>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <description>Visibility of an objective, e.g. &#39;public&#39;, &#39;team&#39;, &#39;private&#39;.</description>
    <label>Visibility</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Task__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

default/objects/Task__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Objective task is for</description>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>tasks</relationshipLabel>
    <relationshipName>tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order of this Task relative to its siblings.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of task e.g. &#39;active&#39;, &#39;done&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/repositories/ObjectiveRepository.cls
/**
 * Utility methods for database operations with Objectives.
 */
public class ObjectiveRepository {

    public static void deleteRecord(Objective__c objective) {
        delete objective;
    }

    /**
     * Gets the details of an objective by ID.
     */
    public static Objective__c get(Id objectiveId) {
        List<Objective__c> objectives = [
            SELECT
                Id,
                CreatedById,
                Category__c,
                Company_Objective__c,
                Closed_Date__c,
                Created_Date__c,
                Description__c,
                End_Date__c,
                Priority__c,
                Review_Date__c,
                Status__c,
                Team_Member__c,
                Title__c,
                Visibility__c,
                (
                    SELECT
                        Id,
                        Content__c,
                        Status__c,
                        Order__c
                    FROM Tasks__r
                    ORDER BY Order__c
                )
            FROM Objective__c
            WHERE Id = :objectiveId
            ORDER BY Created_Date__c
        ];
        return objectives.isEmpty() ? null : objectives[0];
    }

    /**
     * Gets the details of objectives by a set of IDs.
     */
    public static List<Objective__c> get(Set<Id> objectiveIds) {
        return [
            SELECT Id,
                CreatedById,
                Category__c,
                Company_Objective__c,
                Closed_Date__c,
                Created_Date__c,
                Description__c,
                End_Date__c,
                Priority__c,
                Review_Date__c,
                Status__c,
                Team_Member__c,
                Title__c,
                Visibility__c,
                (
                    SELECT Id,
                        Content__c,
                        Status__c,
                        Order__c
                    FROM Tasks__r
                    ORDER BY Order__c
                )
            FROM Objective__c
            WHERE Id IN :objectiveIds
        ];
    }

    /**
     * Gets the details of all of a team member's objectives.
     */
    public static List<Objective__c> getForTeamMember(Id tmId) {
        List<Objective__c> objectives = [
            SELECT Id,
                CreatedById,
                Category__c,
                Company_Objective__c,
                Closed_Date__c,
                Created_Date__c,
                Description__c,
                End_Date__c,
                Priority__c,
                Review_Date__c,
                Status__c,
                Team_Member__c,
                Title__c,
                Visibility__c,
                (
                    SELECT
                        Id,
                        Content__c,
                        Status__c,
                        Order__c
                    FROM Tasks__r
                    ORDER BY Order__c
                )
            FROM Objective__c
            WHERE Team_Member__c = :tmId
            ORDER BY Created_Date__c
        ];
        return objectives;
    }

    /**
     * Gets the details of all of a team member's objectives.
     */
    public static List<Objective__c> getActiveForTeamMembers(Set<Id> tmIds) {
        List<Objective__c> objectives = [
            SELECT
                Id,
                CreatedById,
                Category__c,
                Company_Objective__c,
                Closed_Date__c,
                Created_Date__c,
                Description__c,
                End_Date__c,
                Priority__c,
                Review_Date__c,
                Status__c,
                Team_Member__c,
                Title__c,
                Visibility__c,
                (
                    SELECT
                        Id,
                        Content__c,
                        Status__c,
                        Order__c
                    FROM Tasks__r
                    ORDER BY Order__c
                )
            FROM Objective__c
            WHERE Team_Member__c IN :tmIds
            AND Status__c = :ObjectiveUtils.STATUS_ACTIVE
            ORDER BY Created_Date__c
        ];
        return objectives;
    }
}