default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>e.g. Company, Personal, Career</description>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Company_Objective__c.field-meta.xml
<CustomField>
    <fullName>Company_Objective__c</fullName>
    <description></description>
    <label>Company Objective</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date the objective should be completed by</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <description>Date the objective should be reviewed</description>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <description>Visibility of an objective, e.g. &#39;public&#39;, &#39;team&#39;, &#39;private&#39;.</description>
    <label>Visibility</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/builders/ObjectiveRecordBuilderTest.cls
@isTest
public class ObjectiveRecordBuilderTest {

    @isTest
    private static void testBuild() {

        // GIVEN an objective to build
        ObjectiveModel objective = ObjectiveTestUtils.getMockObjective();

        // WHEN I build it to a record, including a status override
        Objective__c record = new ObjectiveRecordBuilder(objective)
                .setStatus('Closed')
                .save()
                .build();

        // THEN it has the expected properties
        System.assertNotEquals(null, record.Id);
        System.assertEquals(objective.title, record.Title__c);
        System.assertEquals(objective.description, record.Description__c);
        System.assertEquals(objective.category, record.Category__c);
        System.assertEquals(objective.companyObjective, record.Company_Objective__c);
        System.assertEquals(DateUtils.stringToDate(objective.endDate), record.End_Date__c);
        System.assertEquals(objective.priority, record.Priority__c);
        System.assertEquals('Closed', record.Status__c);
        System.assertEquals(objective.tmId, record.Team_Member__c);
        System.assertEquals(objective.visibility, record.Visibility__c);
        System.assertEquals(DateUtils.stringToDate(objective.reviewDate),record.Review_Date__c);
    }
}