default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Task__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

default/objects/Task__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Objective task is for</description>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>tasks</relationshipLabel>
    <relationshipName>tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order of this Task relative to its siblings.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of task e.g. &#39;active&#39;, &#39;done&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/builders/TaskModelBuilderTest.cls
@isTest
public class TaskModelBuilderTest {

    @isTest
    private static void testBuildTasks_NoTasks() {
        // GIVEN an empty list of Tasks
        List<Task__c> tasks = new List<Task__c>();
        // WHEN building TaskModels from this list
        List<TaskModel> taskModels = TaskModelBuilder.buildTasks(tasks);
        // THEN none are returned
        System.assertEquals(0, taskModels.size());
    }

    @isTest
    private static void testBuildTasks() {

        // GIVEN a list of Tasks relating to an Objective
        Objective__c objective = new Objective__c(
            Title__c = 'Do a thing'
        );
        insert objective;
        Task__c task1 = new Task__c(
            Objective__c = objective.Id,
            Content__c = 'Get this test to pass',
            Status__c = TaskUtils.STATUS_ACTIVE,
            Order__c = 1
        );
        Task__c task2 = new Task__c(
            Objective__c = objective.Id,
            Content__c = 'Ensure coverage is adequate',
            Status__c = TaskUtils.STATUS_COMPLETED,
            Order__c = 1
        );
        List<Task__c> tasks = new List<Task__c> { task1, task2 };
        insert tasks;

        // WHEN building TaskModels from this list
        List<TaskModel> taskModels = TaskModelBuilder.buildTasks(tasks);

        // THEN all my Tasks are converted to TaskModels
        System.assertEquals(2, taskModels.size());
        System.assertEquals(task1.Id, taskModels[0].id);
        System.assertEquals(task1.Content__c, taskModels[0].content);
        System.assertEquals(false, taskModels[0].complete);
        System.assertEquals(task2.Id, taskModels[1].id);
        System.assertEquals(task2.Content__c, taskModels[1].content);
        System.assertEquals(true, taskModels[1].complete);
    }

}