default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/rules/ObjectiveStatusRule.cls
/**
 * Validation rule for determining whether an Objective is in the desired status.
 */
public class ObjectiveStatusRule implements ValidationRule {

    private String objectiveId;
    private String status;

    public ObjectiveStatusRule(String objectiveId, String status) {
        this.objectiveId = objectiveId;
        this.status = status;
    }

    public Boolean isValid() {
        Objective__c record = ObjectiveRepository.get(objectiveId);
        return record != null && record.Status__c == status;
    }

    public ErrorModel createErrorModel() {
        String errorMessage = String.format(
                Label.Objective_Status_Not_As_Expected,
                new List<String>{ status }
        );
        return new ErrorModel(HttpUtils.STATUS_FORBIDDEN, errorMessage, '');
    }
}