default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>e.g. Company, Personal, Career</description>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>Date on which the objective was closed</description>
    <label>Closed Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Objective__c/fields/Company_Objective__c.field-meta.xml
<CustomField>
    <fullName>Company_Objective__c</fullName>
    <description></description>
    <label>Company Objective</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Objective was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Objective__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date the objective should be completed by</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <description>Date the objective should be reviewed</description>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <description>Visibility of an objective, e.g. &#39;public&#39;, &#39;team&#39;, &#39;private&#39;.</description>
    <label>Visibility</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Task__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Objective task is for</description>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>tasks</relationshipLabel>
    <relationshipName>tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of task e.g. &#39;active&#39;, &#39;done&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/builders/ObjectiveModelBuilder.cls
/**
 * Helper for building ObjectiveModels from Objective__c records.
 */
public class ObjectiveModelBuilder {

    /**
     * Given a list of Objective__c records, builds a list of ObjectiveModels.
     */
    public static List<ObjectiveModel> build(List<Objective__c> objectives) {

        // Build creator models
        Set<Id> creatorUsers = new Set<Id>();
        for (Objective__c objective : objectives) {
            creatorUsers.add(objective.CreatedById);
        }

        // Locate conversations
        Map<Id, Objective__c> objectivesById = new Map<Id, Objective__c>(objectives);
        Map<Id, Id> conversationsByObjectiveId =
                ObjectiveUtils.getConversationIds(objectivesById.keySet());

        // Find team member records for creators
        List<fHCM2__Team_Member__c> creators =
                TeamMemberRepository.getTeamMembersForUsers(creatorUsers);

        // Find collaborators
        Map<Id, List<ObjectiveCollaboratorModel>> collaborators =
                ObjectiveCollaboratorUtils.getCollaboratorsFor(objectives);

        // Match creators to objectives
        Map<Objective__c, fHCM2__Team_Member__c> creatorsByObjective =
                new Map<Objective__c, fHCM2__Team_Member__c>();
        for (Objective__c objective : objectives) {
            for (fHCM2__Team_Member__c creator : creators) {
                if (objective.CreatedById == creator.fHCM2__User__c) {
                    creatorsByObjective.put(objective, creator);
                }
            }
        }

        // Build models
        List<ObjectiveModel> models = new List<ObjectiveModel>();
        for (Objective__c objective : objectives) {
            models.add(build(
                    objective,
                    creatorsByObjective.get(objective),
                    collaborators.get(objective.Id),
                    conversationsByObjectiveId.get(objective.Id)
            ));
        }
        return models;
    }

    /**
     * Given an Objective__c record, builds an ObjectiveModel.
     */
    public static ObjectiveModel build(Objective__c objective) {
        return build(
                objective,
                TeamMemberRepository.getTeamMemberForUser(objective.CreatedById),
                ObjectiveCollaboratorUtils.getCollaboratorsFor(objective),
                ObjectiveUtils.getConversationId(objective.Id)
        );
    }

    /**
     * Builds an ObjectiveModel from its components:
     *  - Objective record
     *  - Creator
     *  - Collaborators
     *  - Conversation ID
     */
    public static ObjectiveModel build(
            Objective__c objective,
            fHCM2__Team_Member__c creator,
            List<ObjectiveCollaboratorModel> collaborators,
            Id conversationId) {

        ObjectiveModel model = new ObjectiveModel();

        model.id = objective.Id;
        model.conversationId = conversationId;
        model.title = objective.Title__c;
        model.status = objective.Status__c;
        model.tmId = objective.Team_Member__c;
        model.priority = objective.Priority__c;
        model.category = objective.Category__c;
        model.companyObjective = objective.Company_Objective__c;
        model.visibility = objective.Visibility__c;
        model.description = objective.Description__c;
        model.creator = TeamMemberUtils.createPerson(creator);
        model.endDate = DateUtils.datetimeToStringInUserTimeZone(objective.End_Date__c);
        model.createdDate = DateUtils.datetimeToStringInUserTimeZone(objective.Created_Date__c);
        model.closedDate = DateUtils.datetimeToStringInUserTimeZone(objective.Closed_Date__c);
        model.reviewDate = DateUtils.datetimeToStringInUserTimeZone(objective.Review_Date__c);
        model.tasks = TaskModelBuilder.buildTasks(objective.Tasks__r);
        model.collaborators = collaborators;

        return model;
    }

}