default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/objectives/rules/CanCloseObjectiveRule.cls
public class CanCloseObjectiveRule implements ValidationRule {

    private String objectiveId;

    public CanCloseObjectiveRule(String objectiveId) {
        this.objectiveId = objectiveId;
    }

    public Boolean isValid() {
        Objective__c objective = ObjectiveRepository.get(objectiveId);
        Viewport viewport;

        try {
            viewport = new Viewport(objective.Team_Member__c);
        } catch (Exception e) {
            return false;
        }

        return viewport.isTeamMember() || viewport.isManager();
    }

    public ErrorModel createErrorModel() {
        return new ErrorModel(HttpUtils.STATUS_FORBIDDEN, Label.Objective_Close_Denied, '');
    }

}