default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>e.g. Company, Personal, Career</description>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date the objective should be completed by</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <description>Date the objective should be reviewed</description>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <description>Visibility of an objective, e.g. &#39;public&#39;, &#39;team&#39;, &#39;private&#39;.</description>
    <label>Visibility</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/test-utils/ObjectiveTestUtils.cls
@isTest
public class ObjectiveTestUtils {

    public class ObjectiveBuilder {
        private Objective__c item;

        public ObjectiveBuilder() {
            item = new Objective__c();
        }

        public ObjectiveBuilder setCategory(String category) {
            item.Category__c = category;
            return this;
        }

        public ObjectiveBuilder setDescription(String description) {
            item.Description__c = description;
            return this;
        }

        public ObjectiveBuilder setPriority(String priority) {
            item.Priority__c = priority;
            return this;
        }

        public ObjectiveBuilder setEndDate(Date endDate) {
            item.End_Date__c = endDate;
            return this;
        }

        public ObjectiveBuilder setReviewDate(Date reviewDate) {
            item.Review_Date__c = reviewDate;
            return this;
        }

        public ObjectiveBuilder setStatus(String status) {
            item.Status__c = status;
            return this;
        }

        public ObjectiveBuilder setTeamMember(Id tmId) {
            item.Team_Member__c = tmId;
            return this;
        }

        public ObjectiveBuilder setTitle(String title) {
            item.Title__c = title;
            return this;
        }

        public ObjectiveBuilder setVisibility(String visibility) {
            item.Visibility__c = visibility;
            return this;
        }

        public ObjectiveBuilder save() {
            upsert item;
            item = ObjectiveRepository.get(item.Id);
            return this;
        }

        public ObjectiveModel build() {
            return ObjectiveModelBuilder.build(item);
        }
    }

    public static ObjectiveModel getMockObjective() {
        fHCM2__Team_Member__c viewer = new TeamMemberTestUtils.TeamMemberBuilder()
                .setUser(UserInfo.getUserId())
                .setName('Wilma Worm')
                .build();

        ObjectiveModel om = new ObjectiveModel();

        // Populate with some mock data
        om.category = 'Category';
        om.description = 'Some description';
        om.endDate = '2019-11-12';
        om.priority = 'High';
        om.companyObjective = 'Customer Focus';
        om.reviewDate = '2019-11-12';
        om.status = 'Draft';
        om.tmId = viewer.Id;
        om.title = 'Something I might do';
        om.visibility = 'Private';
        om.tasks = new List<TaskModel>();

        return om;
    }

    public static void addMockTask(ObjectiveModel om, String content) {
        TaskModel taskModel = createTaskModel(content, false);
        om.tasks.add(taskModel);
    }

    public static TaskModel createTaskModel(String content, Boolean complete) {
        TaskModel taskModel = new TaskModel();
        taskModel.content = content;
        taskModel.complete = complete;
        return taskModel;
    }

}