default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/feedback/builders/ObjectiveActivatedEventBuilder.cls
public class ObjectiveActivatedEventBuilder extends FeedEventBuilder {

    public override FeedItemModel addDetails(
            FeedItemModel item,
            Id viewerId,
            SObject subject) {

        Objective__c objective = (Objective__c) subject;
        item.event.processTitle = Label.Objectives_Process_Name;
        item.event.url = ObjectiveUrlUtils.getObjectivePageUrl(
                objective.Team_Member__c, objective.Id);
        item.event.linkText = objective.Title__c;
        item.content = getContent(viewerId, item.event.actor);
        return item;
    }

    @TestVisible
    private String getContent(Id viewerId, PersonModel actor) {
        return viewerId == actor.id
                ? Label.Objective_Activated_Event_Message_You
                : String.format(
                        Label.Objective_Activated_Event_Message_Named,
                        new List<String>{actor.firstName}
                );
    }
}