default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/classes/objectives/rest/ObjectiveCloseRestTest.cls
@IsTest
public class ObjectiveCloseRestTest {

    private static ObjectiveModel om;
    private static fHCM2__Team_Member__c subject;

    private static void setUp() {
        om = ObjectiveTestUtils.getMockObjective();
        subject = TeamMemberRepository.get(om.tmId);
    }

    //==========================================================================
    // Utilities
    //==========================================================================

    private static String buildURI(String objectiveId) {
        return '/' + ObjectiveCloseRest.OBJECTIVE_PARAM
                + '/' + objectiveId
                + '/close';
    }

    //==========================================================================
    // Test Methods
    //==========================================================================

    @isTest
    private static void testCloseObjective() {

        // GIVEN a draft objective
        setUp();
        Objective__c obj = new Objective__c(
            Title__c = 'Ceci n\'est pas un objectif',
            Team_Member__c = subject.Id,
            Status__c = 'Active'
        );
        insert obj;

        // WHEN I try to close it
        RestTestUtils.setupRestContext('POST', buildURI(obj.Id));
        ObjectiveCloseRest.closeObjective();
        EditObjectiveResponseModel response = (EditObjectiveResponseModel) RestTestUtils.getResponseBody(
                EditObjectiveResponseModel.class);

        // THEN the response code is OK
        System.assertEquals(HttpUtils.STATUS_OK, response.getStatusCode());

        // AND the status has been changed to close
        System.assertEquals(ObjectiveUtils.STATUS_CLOSED, response.objective.status);

        // AND the response does not contain an error
        System.assertEquals(null, response.error);
    }
}