default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Current_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The version number of the Comment Version which represents the current form of this Comment.</description>
    <label>Current Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Comment_Version__c/Comment_Version__c.object-meta.xml
<CustomObject>
    <description>The contents of a Comment at one point in time.</description>
    <label>Comment Version</label>
    <nameField>
        <displayFormat>Comment Version {0}</displayFormat>
        <label>Comment Version #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comment Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment_Version__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>The Comment of which this is a version.</description>
    <label>Feedback Item</label>
    <referenceTo>Comment__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment_Version__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of this Comment Version.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

default/objects/Comment_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of this Comment Version.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/fHCM2__Policy__c/fields/Allow_Edit_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Allow_Edit_Feedback__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not Comments can be edited.</description>
    <inlineHelpText>Whether or not Comments can be edited.</inlineHelpText>
    <label>Allow Edit</label>
    <type>Checkbox</type>
</CustomField>

default/classes/feedback/notifications/EditedCommentNotificationTest.cls
@isTest
public class EditedCommentNotificationTest {

    private static fHCM2__Team_Member__c subject;
    private static fHCM2__Team_Member__c viewer;
    private static FeedItemModel feedback;
    private static ConversationModel conversation;

    private static void setUp() {
        fHCM2__Policy__c pol = new fHCM2__Policy__c(Allow_Edit_Feedback__c = true);
        insert pol;

        viewer = new TeamMemberTestUtils.TeamMemberBuilder()
                .setName('Wilma Worm')
                .setPolicy(pol.Id)
                .setUser(UserInfo.getUserId())
                .build();
        subject = viewer;

        conversation = new FeedbackTestUtils.ConversationBuilder()
                .setSubject(subject.Id)
                .addParticipant(subject)
                .addParticipant(viewer)
                .save()
                .build();

        feedback = new FeedbackTestUtils.FeedbackBuilder()
                .setAuthor(viewer.Id)
                .setContent('<p>Hello there</p>')
                .setConversation(conversation.id)
                .save()
                .build();
    }

    @isTest
    private static void testBuildBody() {

        // GIVEN some Feedback about a Team Member
        setUp();

        // AND some edit that has been made about it
        Comment_Version__c newVersion = new Comment_Version__c(
                Comment__c = feedback.id,
                Content__c = '<p>Well hello there</p>',
                Version__c = 2
        );
        insert newVersion;

        Comment__c feedbackRecord = FeedbackRepository.getFeedback(feedback.id);
        feedbackRecord.Current_Version__c = 2;
        update feedbackRecord;

        feedback.content = newVersion.Content__c;

        // WHEN I build the body for the Notification about it
        Notification notification = EditedCommentNotification.create(
                feedbackRecord.Versions__r[1], feedback);

        // THEN it is of the expected format
        System.assert(Pattern.matches(
                '(?s)'                                  // make dot match newlines
                        + 'Wilma Worm'
                        + '.*\\.'                       // end of intro line
                        + '<p>.*?'
                        + '<p>Hello there</p>'          // previous content
                        + '</p><br /><p>.*?'
                        + '<p>Well hello there</p>'     // new content
                        + '</p><br />.*?'
                        + String.valueOf(subject.Id)    // subject Id in link
                        + '.*?',
                notification.body
        ));
    }
}