default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <description>The conversation to which this comment belongs.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/common/batches/ContentDocumentDeletionBatchTest.cls
/**
 * Tests exercising the ContentDocument deletion batch.
 */
@isTest
public class ContentDocumentDeletionBatchTest {

    private static Comment__c feedback;
    private static Conversation__c conversation;
    private static ContentDocument document;

    private static void setUp() {
        conversation = new Conversation__c();
        insert conversation;

        feedback = new Comment__c(Conversation__c = conversation.Id);
        insert feedback;

        ContentVersion version = FileTestUtils.createDefaultFileLinkedTo(feedback.Id);
        document = FileRepository.getContentDocumentById(version.ContentDocumentId);
    }

    @isTest
    private static void testDeleteBatch() {

        // GIVEN I have some ContentDocument
        setUp();

        // AND a ContentDocument deletion batch ready to execute
        ContentDocumentDeletionBatch batch = new ContentDocumentDeletionBatch(document.Id);
        Database.QueryLocator locator = batch.start(null);
        List<ContentDocument> docsForDeleting = new List<ContentDocument>();
        Database.QueryLocatorIterator iterator = locator.iterator();
        while (iterator.hasNext()) {
            docsForDeleting.add((ContentDocument) iterator.next());
        }

        // WHEN I use the batch job to delete the document immediately
        batch.execute(null, docsForDeleting);
        batch.finish(null);

        // THEN it no longer exists
        System.assertEquals(null, FileRepository.getContentDocumentById(document.Id));
    }
}