default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this comment.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

default/classes/feedback/rules/HasEditFeedbackPermissionRule.cls
/**
 * Validation rule for determining whether a viewer has permission to edit
 * a Feedback item.
 */
public class HasEditFeedbackPermissionRule implements ValidationRule {

    protected Viewport viewport;
    private FeedItemModel item;

    public HasEditFeedbackPermissionRule(FeedItemModel item) {
        this.item = item;
    }

    public Boolean isValid() {

        viewport = new Viewport();

        Id tmId = viewport.getViewerTeamMemberId();
        Comment__c feedback = FeedbackRepository.getFeedback(item.id);

        if (feedback.Author__c != tmId) {
            // Current user is not the author
            return false;
        }

        // Check permissions in viewer policy
        return new Viewport().canViewerEditFeedback();
    }

    public ErrorModel createErrorModel() {
        return new ErrorModel(
                HttpUtils.STATUS_FORBIDDEN, Label.Comment_Edit_Denied, '');
    }

}