default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <description>The conversation to which this comment belongs.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/common/rest/FilesRestTest.cls
/**
 * Tests exercising the Files REST controller.
 */
@isTest
public class FilesRestTest {

    private static Comment__c feedback;
    private static Conversation__c conversation;
    private static ContentVersion version;
    private static ContentDocument document;

    private static void setUp() {
        conversation = new Conversation__c();
        insert conversation;
        feedback = new Comment__c(Conversation__c = conversation.Id);
        insert feedback;

        version = FileTestUtils.createDefaultFileLinkedTo(feedback.Id);
        document = FileRepository.getContentDocumentById(version.ContentDocumentId);
    }

    @isTest
    private static void testGetFileLink () {

        // GIVEN I want to view a File that belongs to me
        setUp();
        RestTestUtils.setupRestContext('GET', '/file/' + document.Id);

        // WHEN I make the request
        FilesRest.getFileLink();
        FileLinkResponseModel response =
                (FileLinkResponseModel) RestTestUtils.getResponseBody(
                        FileLinkResponseModel.class);

        // THEN the operation is allowed
        System.assertEquals(HttpUtils.STATUS_OK, response.getStatusCode());

        // AND I receive the correct information
        System.assert(response.url.contains(document.Id));
    }
}