default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this comment.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Comment__c/fields/Author_Type__c.field-meta.xml
<CustomField>
    <fullName>Author_Type__c</fullName>
    <description>The role of the comment author. Values are assigned programmatically.</description>
    <label>Author Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/Comment__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <description>The conversation to which this comment belongs.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Comment was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Comment__c/fields/Current_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The version number of the Comment Version which represents the current form of this Comment.</description>
    <label>Current Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Comment_Version__c/Comment_Version__c.object-meta.xml
<CustomObject>
    <description>The contents of a Comment at one point in time.</description>
    <label>Comment Version</label>
    <nameField>
        <displayFormat>Comment Version {0}</displayFormat>
        <label>Comment Version #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comment Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment_Version__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>The Comment of which this is a version.</description>
    <label>Feedback Item</label>
    <referenceTo>Comment__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment_Version__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of this Comment Version.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

default/objects/Comment_Version__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Comment Version was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Comment_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of this Comment Version.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Participant__c/Conversation_Participant__c.object-meta.xml
<CustomObject>
    <description>Junction object linking a Conversation to a Team Member participating in it.</description>
    <label>Conversation Participant</label>
    <nameField>
        <displayFormat>Participant-{0000}</displayFormat>
        <label>Participant #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Participant__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The conversation being participated in.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Conversation Participants</relationshipLabel>
    <relationshipName>Conversation_Participants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Conversation_Participant__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Team Member who is doing the participating.</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Conversation Participants</relationshipLabel>
    <relationshipName>Conversation_Participants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>A container for comments, etc. used by Continuous Feedback in Performance Management.</description>
    <label>(Deprecated) Feedback Item</label>
    <nameField>
        <displayFormat>Feedback-{00000}</displayFormat>
        <label>Feedback Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(Deprecated) Feedback Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Feedback__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this feedback.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Feedback Items</relationshipLabel>
    <relationshipName>Feedback_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Feedback__c/fields/Author_Type__c.field-meta.xml
<CustomField>
    <fullName>Author_Type__c</fullName>
    <description>The role of the feedback author. Values are assigned programmatically.</description>
    <label>Author Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/Feedback__c/fields/Current_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The version number of the Feedback Item Version which represents the current form of this Feedback Item.</description>
    <label>Current Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Feedback_Version__c/Feedback_Version__c.object-meta.xml
<CustomObject>
    <description>The contents of a Feedback Item at one point in time.</description>
    <label>(Deprecated) Feedback Item Version</label>
    <nameField>
        <displayFormat>Feedback Version {0}</displayFormat>
        <label>Feedback Version #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(Deprecated) Feedback Item Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Feedback_Version__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of this Feedback Item Version.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

default/objects/Feedback_Version__c/fields/Feedback_Item__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Item__c</fullName>
    <description>The Feedback Item of which this is a version.</description>
    <label>Feedback Item</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Feedback_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of this Feedback Item Version.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Team_Member_Feedback__c/Team_Member_Feedback__c.object-meta.xml
<CustomObject>
    <description>Junction object linking a Feedback Item to a Team Member.</description>
    <label>(Deprecated) Team Member Feedback</label>
    <nameField>
        <displayFormat>TM Feedback #{00}</displayFormat>
        <label>Team Member Feedback #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(Deprecated) Team Member Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Team_Member_Feedback__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <label>Feedback Item</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Team Member Feedback</relationshipLabel>
    <relationshipName>Team_Member_Feedback</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Team_Member_Feedback__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Team Member Feedback</relationshipLabel>
    <relationshipName>Team_Member_Feedback</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/PostInstallClassTest.cls
@isTest
public class PostInstallClassTest {

    @TestSetup
    private static void setup() {

        // Team Members
        fHCM2__Team_Member__c manager = new fHCM2__Team_Member__c(
            Name = 'Manager'
        );
        insert manager;
        fHCM2__Team_Member__c tm1 = new fHCM2__Team_Member__c(
            Name = 'Alfred',
            fHCM2__Manager__c = manager.Id
        );
        fHCM2__Team_Member__c tm2 = new fHCM2__Team_Member__c(
            Name = 'Betty',
            fHCM2__Manager__c = manager.Id
        );
        insert new List<fHCM2__Team_Member__c> { tm1, tm2 };

        // Feedback Items
        Feedback__c feedback1 = new Feedback__c(
            Author__c = tm1.Id,
            Author_Type__c = 'Self',
            Current_Version__c = 2
        );
        Feedback__c feedback2 = new Feedback__c(
            Author__c = tm2.Id,
            Author_Type__c = 'Self',
            Current_Version__c = 2
        );
        insert new List<Feedback__c> { feedback1, feedback2 };

        // Override the CreatedDate of the Feedback Items
        Test.setCreatedDate(feedback1.Id, DateTime.newInstance(2020, 1, 1));
        Test.setCreatedDate(feedback2.Id, DateTime.newInstance(2020, 2, 2));

        // Feedback Versions
        Feedback_Version__c feedback1v1 = new Feedback_Version__c(
            Content__c = 'Feedback on Alfred (v1)',
            Feedback_Item__c = feedback1.Id,
            Version__c = 1
        );
        Feedback_Version__c feedback1v2 = new Feedback_Version__c(
            Content__c = 'Feedback on Alfred (v2)',
            Feedback_Item__c = feedback1.Id,
            Version__c = 2
        );
        Feedback_Version__c feedback2v1 = new Feedback_Version__c(
            Content__c = 'Feedback on Betty (v1)',
            Feedback_Item__c = feedback2.Id,
            Version__c = 1
        );
        Feedback_Version__c feedback2v2 = new Feedback_Version__c(
            Content__c = 'Feedback on Betty (v2)',
            Feedback_Item__c = feedback2.Id,
            Version__c = 2
        );
        insert new List<Feedback_Version__c> {
                feedback1v1, feedback1v2, feedback2v1, feedback2v2 };

        // Override the CreatedDate of the Feedback Versions
        Test.setCreatedDate(feedback1v1.Id, DateTime.newInstance(2020, 1, 1));
        Test.setCreatedDate(feedback1v2.Id, DateTime.newInstance(2020, 2, 2));
        Test.setCreatedDate(feedback2v1.Id, DateTime.newInstance(2020, 3, 3));
        Test.setCreatedDate(feedback2v2.Id, DateTime.newInstance(2020, 4, 4));

        // Team Member Feedback (junctions)
        Team_Member_Feedback__c junction1 = new Team_Member_Feedback__c(
            Feedback__c = feedback1.Id,
            Team_Member__c = tm1.Id
        );
        Team_Member_Feedback__c junction2 = new Team_Member_Feedback__c(
            Feedback__c = feedback2.Id,
            Team_Member__c = tm2.Id
        );
        insert new List<Team_Member_Feedback__c> { junction1, junction2 };
    }

    @isTest
    private static void testMigrateLegacyFeedback() {

        // GIVEN some legacy Feedback Items (see @TestSetup method)
        //  (Here we are retrieving the already-inserted records)
        List<fHCM2__Team_Member__c> tms = [
            SELECT Id,
                Name
            FROM fHCM2__Team_Member__c
            ORDER BY Name
        ];
        fHCM2__Team_Member__c tm1 = tms[0];
        fHCM2__Team_Member__c tm2 = tms[1];

        // WHEN the migration is carried out
        Test.startTest();
        PostInstallClass.migrateLegacyFeedback();
        Integer numSoqlQueries = Limits.getQueries();
        Integer numDmlStatements = Limits.getDMLStatements();
        Test.stopTest();

        // THEN a Conversation is created for each subject
        List<Conversation__c> convos = [
            SELECT Id
            FROM Conversation__c
        ];
        System.assertEquals(2, convos.size());

        // AND a Conversation Participant is created for each subject
        // and their manager
        List<Conversation_Participant__c> convoParticipants = [
            SELECT Id
            FROM Conversation_Participant__c
        ];
        System.assertEquals(4, convoParticipants.size());

        // AND a Comment is created for each Feedback Item
        List<Comment__c> comments = [
            SELECT
                Id,
                Author__c,
                Author_Type__c,
                Created_Date__c,
                Current_Version__c
            FROM Comment__c
            ORDER BY Created_Date__c
        ];
        System.assertEquals(2, comments.size());

        // AND all fields are set correctly
        System.assertEquals(tm1.Id, comments[0].Author__c);
        System.assertEquals(tm2.Id, comments[1].Author__c);
        System.assertEquals('Self', comments[0].Author_Type__c);
        System.assertEquals('Self', comments[1].Author_Type__c);
        System.assertEquals(
                DateTime.newInstance(2020, 1, 1), comments[0].Created_Date__c);
        System.assertEquals(
                DateTime.newInstance(2020, 2, 2), comments[1].Created_Date__c);
        System.assertEquals(2, comments[0].Current_Version__c);
        System.assertEquals(2, comments[1].Current_Version__c);

        // AND a Comment Version is created for each Feedback Version
        List<Comment_Version__c> commentVersions = [
            SELECT
                Id,
                Created_Date__c,
                Comment__c,
                Content__c,
                Version__c
            FROM Comment_Version__c
            ORDER BY Created_Date__c
        ];
        System.assertEquals(4, commentVersions.size());

        // AND all fields are set correctly
        System.assertEquals(
                DateTime.newInstance(2020, 1, 1),
                commentVersions[0].Created_Date__c);
        System.assertEquals(
                DateTime.newInstance(2020, 2, 2),
                commentVersions[1].Created_Date__c);
        System.assertEquals(
                DateTime.newInstance(2020, 3, 3),
                commentVersions[2].Created_Date__c);
        System.assertEquals(
                DateTime.newInstance(2020, 4, 4),
                commentVersions[3].Created_Date__c);
        System.assertEquals(comments[0].Id, commentVersions[0].Comment__c);
        System.assertEquals(comments[0].Id, commentVersions[1].Comment__c);
        System.assertEquals(comments[1].Id, commentVersions[2].Comment__c);
        System.assertEquals(comments[1].Id, commentVersions[3].Comment__c);
        System.assertEquals(
                'Feedback on Alfred (v1)', commentVersions[0].Content__c);
        System.assertEquals(
                'Feedback on Alfred (v2)', commentVersions[1].Content__c);
        System.assertEquals(
                'Feedback on Betty (v1)', commentVersions[2].Content__c);
        System.assertEquals(
                'Feedback on Betty (v2)', commentVersions[3].Content__c);
        System.assertEquals(1, commentVersions[0].Version__c);
        System.assertEquals(2, commentVersions[1].Version__c);
        System.assertEquals(1, commentVersions[2].Version__c);
        System.assertEquals(2, commentVersions[3].Version__c);

        // AND the Team Member Feedback junction objects are deleted
        List<Team_Member_Feedback__c> junctions =
                [ SELECT Id FROM Team_Member_Feedback__c ];
        System.assertEquals(0, junctions.size());

        // AND the Feedback Items are deleted
        List<Feedback__c> feedbackItems =
                [ SELECT Id FROM Feedback__c ];
        System.assertEquals(0, feedbackItems.size());

        // AND the Feedback Versions are deleted
        // (due to being children of a master-detail relationship)
        List<Feedback_Version__c> feedbackVersions =
                [ SELECT Id FROM Feedback_Version__c ];
        System.assertEquals(0, feedbackVersions.size());

        // AND only 4 queries were carried out
        System.assertEquals(4, numSoqlQueries);

        // AND only 6 DML statements were carried out
        // (5 inserts and 2 deletes)
        System.assertEquals(7, numDmlStatements);
    }

}