default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this comment.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Comment__c/fields/Author_Type__c.field-meta.xml
<CustomField>
    <fullName>Author_Type__c</fullName>
    <description>The role of the comment author. Values are assigned programmatically.</description>
    <label>Author Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/Comment__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <description>The conversation to which this comment belongs.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Comment was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Comment__c/fields/Current_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The version number of the Comment Version which represents the current form of this Comment.</description>
    <label>Current Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Comment_Version__c/Comment_Version__c.object-meta.xml
<CustomObject>
    <description>The contents of a Comment at one point in time.</description>
    <label>Comment Version</label>
    <nameField>
        <displayFormat>Comment Version {0}</displayFormat>
        <label>Comment Version #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comment Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment_Version__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>The Comment of which this is a version.</description>
    <label>Feedback Item</label>
    <referenceTo>Comment__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment_Version__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of this Comment Version.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

default/objects/Comment_Version__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Comment Version was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Comment_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of this Comment Version.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/feedback/repositories/FeedbackRepository.cls
/**
 * Class for performing database operations with Feedback records.
 */
public class FeedbackRepository {

    /**
     * Performs the 'insert' DML operation on a record.
     */
    public static void insertRecord(Comment__c record) {
        // Set the artificial created date (SPPLDEV-5734)
        record.Created_Date__c = Datetime.now();
        insert record;
    }

    /**
     * Performs the 'update' DML operation on a record.
     */
    public static void updateRecord(Comment__c record) {
        update record;
    }

    /**
     * Performs the 'delete' DML operation on a record.
     */
    public static void deleteRecord(Comment__c record) {
        delete record;
    }

    /**
     * Performs the 'insert' DML operation on a list of records.
     */
    public static void insertRecords(List<Comment__c> records) {

        // Set the artificial created date (SPPLDEV-5734)
        Datetime createdDate = Datetime.now();
        for (Comment__c record : records) {
            record.Created_Date__c = createdDate;
        }

        insert records;
    }

    /**
     * Performs the 'update' DML operation on a list of records.
     */
    public static void updateRecords(List<Comment__c> records) {
        update records;
    }

    /**
     * Performs the 'delete' DML operation on a list of records.
     */
    public static void deleteRecords(List<Comment__c> records) {
        delete records;
    }

    /**
     * Finds the saved Feedback item with the given Id.
     */
    public static Comment__c getFeedback(Id feedbackId) {
        List<Comment__c> feedback = [
            SELECT
                Id,
                Author__c,
                Author_Type__c,
                Conversation__c,
                Created_Date__c,
                Current_Version__c,
                (
                    SELECT
                        Id,
                        Content__c,
                        Created_Date__c,
                        Version__c
                    FROM Versions__r
                    ORDER BY Version__c DESC
                )
            FROM Comment__c
            WHERE Id = :feedbackId
            LIMIT 1
        ];
        return feedback.isEmpty() ? null : feedback.get(0);
    }

    /**
     * Finds all saved Feedback items whose Ids appear in a given Set.
     */
    public static List<Comment__c> getFeedbackWithIds(Set<Id> feedbackIds) {
        return [
            SELECT
                Id,
                Author__c,
                Author_Type__c,
                Conversation__c,
                Created_Date__c,
                Current_Version__c,
                (
                    SELECT
                        Id,
                        Content__c,
                        Created_Date__c,
                        Version__c
                    FROM Versions__r
                    ORDER BY Version__c DESC
                    LIMIT 1
                )
            FROM Comment__c
            WHERE Id IN :feedbackIds
            ORDER BY Created_Date__c DESC
        ];
    }

    /**
     * Finds all saved Feedback items which are part of a set of conversations.
     */
    public static List<Comment__c> getFeedbackWithConversationIds(Set<Id> conversationIds) {
        List<Comment__c> feedback = [
                SELECT
                    Id,
                    Author__c,
                    Author_Type__c,
                    Conversation__c,
                    Created_Date__c,
                    Current_Version__c,
                    (
                        SELECT
                            Id,
                            Content__c,
                            Created_Date__c,
                            Version__c
                        FROM Versions__r
                        ORDER BY Version__c DESC
                        LIMIT 1
                    )
                FROM Comment__c
                WHERE Conversation__c IN :conversationIds
                ORDER BY Created_Date__c DESC
        ];
        return feedback;
    }

}