default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this comment.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Comment__c/fields/Author_Type__c.field-meta.xml
<CustomField>
    <fullName>Author_Type__c</fullName>
    <description>The role of the comment author. Values are assigned programmatically.</description>
    <label>Author Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/Comment__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <description>The conversation to which this comment belongs.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Comment was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Comment__c/fields/Current_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The version number of the Comment Version which represents the current form of this Comment.</description>
    <label>Current Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Comment_Version__c/Comment_Version__c.object-meta.xml
<CustomObject>
    <description>The contents of a Comment at one point in time.</description>
    <label>Comment Version</label>
    <nameField>
        <displayFormat>Comment Version {0}</displayFormat>
        <label>Comment Version #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comment Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment_Version__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>The Comment of which this is a version.</description>
    <label>Feedback Item</label>
    <referenceTo>Comment__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment_Version__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of this Comment Version.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

default/objects/Comment_Version__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Comment Version was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Comment_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of this Comment Version.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Participant__c/Conversation_Participant__c.object-meta.xml
<CustomObject>
    <description>Junction object linking a Conversation to a Team Member participating in it.</description>
    <label>Conversation Participant</label>
    <nameField>
        <displayFormat>Participant-{0000}</displayFormat>
        <label>Participant #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Participant__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The conversation being participated in.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Conversation Participants</relationshipLabel>
    <relationshipName>Conversation_Participants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Conversation_Participant__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Team Member who is doing the participating.</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Conversation Participants</relationshipLabel>
    <relationshipName>Conversation_Participants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Conversation_Subject__c/Conversation_Subject__c.object-meta.xml
<CustomObject>
    <description>Junction object linking a Conversation to its subject record.</description>
    <label>Conversation Subject</label>
    <nameField>
        <displayFormat>Subject-{0000}</displayFormat>
        <label>Subject #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Subject__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The conversation whose subject this links to.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Conversation Subjects</relationshipLabel>
    <relationshipName>Conversation_Subjects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Conversation_Subject__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subject record for a conversation about a Team Member.</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Conversation Subjects</relationshipLabel>
    <relationshipName>Conversation_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>A container for comments, etc. used by Continuous Feedback in Performance Management.</description>
    <label>(Deprecated) Feedback Item</label>
    <nameField>
        <displayFormat>Feedback-{00000}</displayFormat>
        <label>Feedback Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(Deprecated) Feedback Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Feedback__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this feedback.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Feedback Items</relationshipLabel>
    <relationshipName>Feedback_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Feedback__c/fields/Author_Type__c.field-meta.xml
<CustomField>
    <fullName>Author_Type__c</fullName>
    <description>The role of the feedback author. Values are assigned programmatically.</description>
    <label>Author Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/Feedback__c/fields/Current_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The version number of the Feedback Item Version which represents the current form of this Feedback Item.</description>
    <label>Current Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Feedback_Version__c/Feedback_Version__c.object-meta.xml
<CustomObject>
    <description>The contents of a Feedback Item at one point in time.</description>
    <label>(Deprecated) Feedback Item Version</label>
    <nameField>
        <displayFormat>Feedback Version {0}</displayFormat>
        <label>Feedback Version #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(Deprecated) Feedback Item Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Feedback_Version__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of this Feedback Item Version.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

default/objects/Feedback_Version__c/fields/Feedback_Item__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Item__c</fullName>
    <description>The Feedback Item of which this is a version.</description>
    <label>Feedback Item</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Feedback_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of this Feedback Item Version.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Team_Member_Feedback__c/Team_Member_Feedback__c.object-meta.xml
<CustomObject>
    <description>Junction object linking a Feedback Item to a Team Member.</description>
    <label>(Deprecated) Team Member Feedback</label>
    <nameField>
        <displayFormat>TM Feedback #{00}</displayFormat>
        <label>Team Member Feedback #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(Deprecated) Team Member Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Team_Member_Feedback__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <label>Feedback Item</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Team Member Feedback</relationshipLabel>
    <relationshipName>Team_Member_Feedback</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Team_Member_Feedback__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Team Member Feedback</relationshipLabel>
    <relationshipName>Team_Member_Feedback</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/classes/PostInstallClass.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
global class PostInstallClass implements InstallHandler {

    global void onInstall(InstallContext context) {
        migrateLegacyFeedback();
        registerProcess();
        registerProcessViews();
    }

    /**
     * Migrates now-deprecated Feedback Items to the new Comment format.
     *
     * This will only affect customers who installed the very first Performance
     * Management package, before the notion of Conversations was introduced.
     *
     *     Team Member Feedback     -> Junction object no longer needed
     *      |- Feedback                 (we create a parent Conversation and
     *      |- Team Member               a Conversation Subject instead)
     *
     *     Feedback Item            -> Comment
     *      |- Author                   (the manual Created Date field also
     *      |- Author Type               needs to be set)
     *      |- Current Version
     *
     *     Feedback Version         -> Comment Version
     *      |- Content                 (the manual Created Date field also
     *      |- Feedback Item            needs to be set)
     *      |- Version
     */
    public static void migrateLegacyFeedback() {

        // Find all Team Member Feedback records
        List<Team_Member_Feedback__c> junctions = [
            SELECT Id,
                Feedback__c,
                Team_Member__c
            FROM Team_Member_Feedback__c
        ];

        if (junctions.isEmpty()) {
            // Nothing to do!
            return;
        }

        // Find all Feedback Items
        List<Feedback__c> feedbackItems = [
            SELECT
                Id,
                Author__c,
                Author_Type__c,
                CreatedDate,
                Current_Version__c
            FROM Feedback__c
        ];

        // Find all Feedback Versions
        List<Feedback_Version__c> feedbackVersions = [
            SELECT
                Id,
                CreatedDate,
                Content__c,
                Feedback_Item__c,
                Version__c
            FROM Feedback_Version__c
        ];

        // Create a map of Feedback Item ID -> Subject TM ID
        Map<Id, Id> subjectTmIdsByFeedbackId = new Map<Id, Id>();
        for (Team_Member_Feedback__c junction : junctions) {
            subjectTmIdsByFeedbackId.put(
                    junction.Feedback__c,
                    junction.Team_Member__c);
        }

        // Find all unique subject TM IDs
        Set<Id> subjectTmIds = getSubjectsFromJunctions(junctions);

        // Retrieve these Team Members, and their managers
        List<fHCM2__Team_Member__c> subjectTms = [
            SELECT Id,
                fHCM2__Manager__c
            FROM fHCM2__Team_Member__c
            WHERE Id IN :subjectTmIds
        ];

        // Create a Conversation for each subject
        List<Conversation__c> convos = new List<Conversation__c>();
        Map<Id, Conversation__c> conversationsByTmId =
                new Map<Id, Conversation__c>();
        for (Id tmId : subjectTmIds) {
            Conversation__c convo = new Conversation__c();
            convos.add(convo);
            conversationsByTmId.put(tmId, convo);
        }
        insert convos;

        // Create a Conversation Participant for each subject and their manager
        List<Conversation_Participant__c> convoParticipants =
                getConversationParticipants(
                        subjectTms,
                        conversationsByTmId);
        insert convoParticipants;

        // Create a Conversation Subject for each subject
        List<Conversation_Subject__c> convoSubjects =
                new List<Conversation_Subject__c>();
        for (Id tmId : subjectTmIds) {
            Conversation__c convo = conversationsByTmId.get(tmId);
            Conversation_Subject__c convoSubject = new Conversation_Subject__c(
                Conversation__c = convo.Id,
                Team_Member__c = tmId
            );
            convoSubjects.add(convoSubject);
        }
        insert convoSubjects;

        // Create a Comment for each Feedback Item
        List<Comment__c> comments = new List<Comment__c>();
        Map<Id, Comment__c> commentsByFeedbackId = new Map<Id, Comment__c>();
        for (Feedback__c feedbackItem : feedbackItems) {
            Id subjectTmId = subjectTmIdsByFeedbackId.get(feedbackItem.Id);
            Conversation__c convo = conversationsByTmId.get(subjectTmId);
            Comment__c comment = new Comment__c(
                Author__c = feedbackItem.Author__c,
                Author_Type__c = feedbackItem.Author_Type__c,
                Conversation__c = convo.Id,
                Created_Date__c = feedbackItem.CreatedDate,
                Current_Version__c = feedbackItem.Current_Version__c
            );
            comments.add(comment);
            commentsByFeedbackId.put(feedbackItem.Id, comment);
        }
        insert comments;

        // Create a Comment Version for each Feedback Version
        List<Comment_Version__c> commentVersions =
                new List<Comment_Version__c>();
        for (Feedback_Version__c feedbackVersion : feedbackVersions) {
            Id feedbackId = feedbackVersion.Feedback_Item__c;
            Comment__c comment = commentsByFeedbackId.get(feedbackId);
            Comment_Version__c commentVersion = new Comment_Version__c(
                Comment__c = comment.Id,
                Content__c = feedbackVersion.Content__c,
                Created_Date__c = feedbackVersion.CreatedDate,
                Version__c = feedbackVersion.Version__c
            );
            commentVersions.add(commentVersion);
        }
        insert commentVersions;

        // Delete old records
        delete junctions;
        delete feedbackItems;
    }

    /**
     * Gets the set of subject TM IDs from Team_Member_Feedback__c records.
     */
    private static Set<Id> getSubjectsFromJunctions(
            List<Team_Member_Feedback__c> junctions) {
        Set<Id> subjectTmIds = new Set<Id>();
        for (Team_Member_Feedback__c junction : junctions) {
            subjectTmIds.add(junction.Team_Member__c);
        }
        return subjectTmIds;
    }

    /**
     * Gets the list of all Conversation Participants for each Conversation
     * (subject and manager).
     */
    private static List<Conversation_Participant__c> getConversationParticipants(
            List<fHCM2__Team_Member__c> subjectTms,
            Map<Id, Conversation__c> conversationsByTmId) {

        List<Conversation_Participant__c> convoParticipants =
                new List<Conversation_Participant__c>();

        Map<Id, fHCM2__Team_Member__c> subjectTmsById =
                new Map<Id, fHCM2__Team_Member__c>(subjectTms);

        for (Id tmId : subjectTmsById.keySet()) {
            Conversation__c convo = conversationsByTmId.get(tmId);
            fHCM2__Team_Member__c subjectTm = subjectTmsById.get(tmId);
            convoParticipants.add(new Conversation_Participant__c(
                Conversation__c = convo.Id,
                Team_Member__c = subjectTm.Id
            ));
            if (subjectTm.fHCM2__Manager__c != null) {
                convoParticipants.add(new Conversation_Participant__c(
                    Conversation__c = convo.Id,
                    Team_Member__c = subjectTm.fHCM2__Manager__c
                ));
            }
        }

        return convoParticipants;
    }

    public static void registerProcess() {
        fHCM2.HCMProcesses.getProcess('Performance Management', true)
                .setStandaloneApp(true)
                .setPackage('spperfmgmt')
                .setGroup('FairsailProfile')
                .setShowTeamMember(true)
                .setShowManager(true)
                .setUrl('Performance')
                .setVisibilityController('PerformanceVisibilityController')
                .setTilePage('PerformanceTile')
                .register();
        fHCM2.HCMProcesses.saveRegistered();
    }

    public static void registerProcessViews() {
        fHCM2.ProcessViews.register(
                'Performance Management Tile',             // View name
                'tile',                                    // View type
                'Performance Management',                  // Process
                'views/processes/standaloneapp/tile.html', // URL
                true,                                      // Is Default
                1,                                         // Number of columns
                'tile',                                    // View ID
                'Team Member',                             // Team Member or Team
                'tile',                                    // Content type
                null,                                      // Static resource
                true);                                     // Overwrite?
        fHCM2.ProcessViews.saveRegistered();
    }

}