default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this comment.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Comment__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <description>The conversation to which this comment belongs.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/feedback/repositories/FeedbackRepositoryTest.cls
/**
 * Tests exercising the Feedback Repository.
 */
@isTest
public class FeedbackRepositoryTest {

    private static Conversation__c conversation;

    private static void setUp() {
        conversation = new Conversation__c();
        insert conversation;
    }

    @isTest
    private static void testGetFeedback() {

        // GIVEN some saved Feedback
        setUp();
        fHCM2__Team_Member__c author =
                new TeamMemberTestUtils.TeamMemberBuilder().build();

        Comment__c savedFeedback = new Comment__c(
            Author__c = author.Id,
            Conversation__c = conversation.Id
        );
        insert savedFeedback;

        // WHEN I retrieve its properties
        Comment__c retrievedFeedback =
                FeedbackRepository.getFeedback(savedFeedback.Id);

        // THEN I get the same information back
        System.assertEquals(savedFeedback.Id, retrievedFeedback.Id);
        System.assertEquals(savedFeedback.Author__c, retrievedFeedback.Author__c);
    }

    @isTest
    private static void testGetFeedbackWithIds() {

        // GIVEN two saved Feedback items
        setUp();
        Comment__c firstFeedback = new Comment__c(Conversation__c = conversation.Id);
        Comment__c secondFeedback = new Comment__c(Conversation__c = conversation.Id);
        insert new List<Comment__c>{firstFeedback, secondFeedback};

        // AND a set containing their Ids
        Set<Id> ids = new Set<Id>{firstFeedback.Id, secondFeedback.Id};

        // WHEN I retrieve all Feedback items with Ids in this set
        List<Comment__c> feedback = FeedbackRepository.getFeedbackWithIds(ids);

        // THEN I receive a list of two items
        System.assertEquals(2, feedback.size());

        // AND they are my original pair
        Set<Id> retrievedIds = SObjectUtils.getIds((List<SObject>) feedback);
        System.assert(retrievedIds.contains(firstFeedback.Id));
        System.assert(retrievedIds.contains(secondFeedback.Id));
    }
}