default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this comment.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Comment__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <description>The conversation to which this comment belongs.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Comment was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Comment__c/fields/Current_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The version number of the Comment Version which represents the current form of this Comment.</description>
    <label>Current Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Comment_Version__c/Comment_Version__c.object-meta.xml
<CustomObject>
    <description>The contents of a Comment at one point in time.</description>
    <label>Comment Version</label>
    <nameField>
        <displayFormat>Comment Version {0}</displayFormat>
        <label>Comment Version #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comment Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment_Version__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>The Comment of which this is a version.</description>
    <label>Feedback Item</label>
    <referenceTo>Comment__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment_Version__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of this Comment Version.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

default/objects/Comment_Version__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Date the Comment Version was created.</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Comment_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of this Comment Version.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/feedback/builders/FeedItemModelBuilder.cls
public class FeedItemModelBuilder {

    /**
     * Converts a Comment record into a FeedItemModel.
     */
    public static FeedItemModel buildFromComment(
            Comment__c record,
            fHCM2__Team_Member__c author) {

        FeedItemModel model = new FeedItemModel();
        model.id = record.Id;
        model.itemDate = DateUtils.datetimeToStringInUserTimeZone(record.Created_Date__c);
        model.conversationId = record.Conversation__c;

        model.comment = new CommentModel();
        model.comment.version = (Integer) record.Current_Version__c;
        model.comment.author = TeamMemberUtils.createPerson(author);
        if (!record.Versions__r.isEmpty()) {
            model.content = record.Versions__r[0].Content__c;
            model.comment.latestVersionDate = DateUtils.datetimeToStringInUserTimeZone(
                record.Versions__r[0].Created_Date__c);
        }

        return model;
    }

    /**
     * Converts Comment records into FeedItemModels.
     */
    public static List<FeedItemModel> buildFromComments(List<Comment__c> records) {

        // Collect author details in bulk
        Set<Id> authorIds = new Set<Id>();
        for (Comment__c record : records) {
            authorIds.add(record.Author__c);
        }
        Map<Id, fHCM2__Team_Member__c> authors = new Map<Id, fHCM2__Team_Member__c>(
                TeamMemberRepository.get(authorIds));

        // Build models
        List<FeedItemModel> models = new List<FeedItemModel>();
        for (Comment__c record : records) {
            models.add(buildFromComment(record, authors.get(record.Author__c)));
        }
        return models;
    }

    /**
     * Creates a FeedItemModel for each Version of a supplied Comment record.
     */
    public static List<FeedItemModel> buildFromCommentsByVersion(
            Comment__c record,
            fHCM2__Team_Member__c author) {

        List<FeedItemModel> models = new List<FeedItemModel>();
        PersonModel authorPerson = TeamMemberUtils.createPerson(author);

        for (Comment_Version__c version : record.Versions__r) {
            FeedItemModel model = new FeedItemModel();
            model.id = version.Id;
            model.content = version.Content__c;
            model.conversationId = record.Conversation__c;
            model.itemDate =
                    DateUtils.datetimeToStringInUserTimeZone(version.Created_Date__c);

            model.comment = new CommentModel();
            model.comment.version = (Integer) version.Version__c;
            model.comment.author = authorPerson;
            models.add(model);
        }
        return models;
    }

}