default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>A comment within a conversation.</description>
    <label>Comment</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The author of this comment.</description>
    <label>Author</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Comment__c/fields/Author_Type__c.field-meta.xml
<CustomField>
    <fullName>Author_Type__c</fullName>
    <description>The role of the comment author. Values are assigned programmatically.</description>
    <label>Author Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

default/objects/Comment__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <description>The conversation to which this comment belongs.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment__c/fields/Current_Version__c.field-meta.xml
<CustomField>
    <fullName>Current_Version__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The version number of the Comment Version which represents the current form of this Comment.</description>
    <label>Current Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Comment_Version__c/Comment_Version__c.object-meta.xml
<CustomObject>
    <description>The contents of a Comment at one point in time.</description>
    <label>Comment Version</label>
    <nameField>
        <displayFormat>Comment Version {0}</displayFormat>
        <label>Comment Version #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comment Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Comment_Version__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>The Comment of which this is a version.</description>
    <label>Feedback Item</label>
    <referenceTo>Comment__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Comment_Version__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The content of this Comment Version.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

default/objects/Comment_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of this Comment Version.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Participant__c/Conversation_Participant__c.object-meta.xml
<CustomObject>
    <description>Junction object linking a Conversation to a Team Member participating in it.</description>
    <label>Conversation Participant</label>
    <nameField>
        <displayFormat>Participant-{0000}</displayFormat>
        <label>Participant #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Participant__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The conversation being participated in.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Conversation Participants</relationshipLabel>
    <relationshipName>Conversation_Participants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Conversation_Participant__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Team Member who is doing the participating.</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Conversation Participants</relationshipLabel>
    <relationshipName>Conversation_Participants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/classes/feedback/test-utils/FeedbackTestUtils.cls
/**
 * Test utilities supplying Feedback data.
 */
@isTest
public class FeedbackTestUtils {

    public class FeedbackBuilder {

        private Comment__c item;
        private fHCM2__Team_Member__c author;
        private String content;

        public FeedbackBuilder() {
            item = new Comment__c();
        }

        public FeedbackBuilder(Comment__c template) {
            item = template;
        }

        public FeedbackBuilder(FeedItemModel template) {
            item = FeedbackRecordBuilder.build(template, 1);
        }

        public FeedbackBuilder setAuthor(Id authorId) {
            item.Author__c = authorId;
            this.author = TeamMemberRepository.get(authorId);
            return this;
        }

        public FeedbackBuilder setAuthor(fHCM2__Team_Member__c author) {
            item.Author__c = author.Id;
            this.author = author;
            return this;
        }

        public FeedbackBuilder setAuthorType(String authorType) {
            item.Author_Type__c = authorType;
            return this;
        }

        public FeedbackBuilder setContent(String content) {
            this.content = content;
            return this;
        }

        public FeedbackBuilder setConversation(Id conversationId) {
            item.Conversation__c = conversationId;
            return this;
        }

        public FeedbackBuilder save() {

            // Create a new parent Conversation if we don't already have one
            if (item.Conversation__c == null) {
                Conversation__c conversation = new Conversation__c();
                insert conversation;
                item.Conversation__c = conversation.Id;
            }

            // Save item itself
            item.Current_Version__c = 1;
            upsert item;

            // Save Version record
            Comment_Version__c feedbackVersion = new Comment_Version__c(
                    Comment__c = item.Id,
                    Content__c = content,
                    Version__c = 1
            );
            FeedbackVersionRepository.insertRecord(feedbackVersion);

            // Refresh local copy
            item = FeedbackRepository.getFeedback(item.Id);

            return this;
        }

        public FeedItemModel build() {
            return FeedItemModelBuilder.buildFromComment(item, author);
        }
    }

    public class ConversationBuilder {

        private Conversation__c conversation;
        private SubjectModel subject;
        private List<PersonModel> participants;

        public ConversationBuilder() {
            conversation = new Conversation__c();
            participants = new List<PersonModel>();
        }

        public ConversationBuilder setName(String name) {
            conversation.Name = name;
            return this;
        }

        public ConversationBuilder setSubject(Id subjectId) {
            this.subject =
                    ConversationHandlerRegistry.getHandlerForSubject(subjectId)
                            .createSubject();
            return this;
        }

        public ConversationBuilder addParticipant(fHCM2__Team_Member__c tm) {
            participants.add(TeamMemberUtils.createPerson(tm));
            return this;
        }

        public ConversationBuilder addParticipant(Id tmId) {
            participants.add(TeamMemberUtils.createPerson(tmId));
            return this;
        }

        public ConversationBuilder save() {

            // Create Conversation itself
            insert conversation;

            // Create Subject junction
            ConversationUtils.linkSubject(conversation.Id, subject.id);

            // Create Participants junctions
            List<Conversation_Participant__c> participantJunctions =
                    new List<Conversation_Participant__c>();
            for (PersonModel participant : participants) {
                participantJunctions.add(new Conversation_Participant__c(
                    Conversation__c = conversation.Id,
                    Team_Member__c = participant.id
                ));
            }
            insert participantJunctions;

            return this;
        }

        public ConversationModel build() {
            return ConversationModelBuilder.build(
                    conversation,
                    subject,
                    participants,
                    new List<FeedItemModel>());
        }

    }

}