default/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <description>A conversation between Team Members about something.</description>
    <label>Conversation</label>
    <nameField>
        <label>Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Subject__c/Conversation_Subject__c.object-meta.xml
<CustomObject>
    <description>Junction object linking a Conversation to its subject record.</description>
    <label>Conversation Subject</label>
    <nameField>
        <displayFormat>Subject-{0000}</displayFormat>
        <label>Subject #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversation Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Conversation_Subject__c/fields/Conversation__c.field-meta.xml
<CustomField>
    <fullName>Conversation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The conversation whose subject this links to.</description>
    <label>Conversation</label>
    <referenceTo>Conversation__c</referenceTo>
    <relationshipLabel>Conversation Subjects</relationshipLabel>
    <relationshipName>Conversation_Subjects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

default/objects/Conversation_Subject__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Objective which is the subject of the linked Conversation.</description>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Conversation Subjects</relationshipLabel>
    <relationshipName>Conversation_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Conversation_Subject__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subject record for a conversation about a Team Member.</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Conversation Subjects</relationshipLabel>
    <relationshipName>Conversation_Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <displayFormat>Objective-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Objective__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>Date on which the objective was closed</description>
    <label>Closed Date</label>
    <type>DateTime</type>
</CustomField>

default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of objective. e.g. &#39;Active&#39;, &#39;Draft&#39;, &#39;Complete&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Objective__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team member the objective is for</description>
    <label>Team Member</label>
    <referenceTo>fHCM2__Team_Member__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Objective__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>240</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Task__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

default/objects/Task__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Objective task is for</description>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>tasks</relationshipLabel>
    <relationshipName>tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

default/objects/Task__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order of this Task relative to its siblings.</description>
    <label>Version</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of task e.g. &#39;active&#39;, &#39;done&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/utils/ObjectiveUtils.cls
/**
 * Utilities for working with objectives.
 */
public class ObjectiveUtils {

    public class ObjectiveNotFoundException extends Exception {}

    public static final String OBJECTIVE_TYPE =
            NamespaceUtils.getNamespacePrefix() + 'Objective__c';

    private static final String OBJECTIVES_PAGE =
            '/apex/Performance#/tm/{0}/objectives/{1}';

    public static final String OBJECTIVES_PROCESS_NAME = 'Objectives';

    public static final String STATUS_DRAFT = 'Draft';
    public static final String STATUS_ACTIVE = 'Active';
    public static final String STATUS_CLOSED = 'Closed';
    public static final String VISIBILITY_PRIVATE = 'Private';
    public static final String VISIBILITY_PUBLIC = 'Public';

    /**
     * Given a TM ID, finds and builds all objectives which are visible to the
     * viewer.
     */
    public static List<ObjectiveModel> getVisibleObjectives(Id tmId) {

        // Get all objectives
        List<Objective__c> objectives = ObjectiveRepository.getForTeamMember(tmId);

        // Remove those which aren't visible to me
        Id viewerUserId = UserInfo.getUserId();
        List<Objective__c> filteredObjectives = new List<Objective__c>();
        for (Objective__c objective : objectives) {
            if (isVisibleToMe(objective, viewerUserId)) {
                filteredObjectives.add(objective);
            }
        }

        // Build models & return
        return ObjectiveModelBuilder.build(filteredObjectives);
    }

    /**
     * Creates a new objective in the database, in DRAFT state.
     */
    public static Objective__c createObjective(ObjectiveModel om) {
        return new ObjectiveRecordBuilder(om)
                .setStatus(ObjectiveUtils.STATUS_DRAFT)
                .save()
                .build();
    }

    /**
     * Updates an existing objective in the database, without respecting status
     * changes.
     */
    public static Objective__c updateObjective(ObjectiveModel om) {
        return new ObjectiveRecordBuilder(om)
                .save()
                .build();
    }

    /**
     * Updates an existing objective in the database, respecting status
     * changes.
     */
    public static Objective__c updateObjectiveAndActivate(ObjectiveModel om) {
        Objective__c objective = new ObjectiveRecordBuilder(om)
                .setStatus(ObjectiveUtils.STATUS_ACTIVE)
                .save()
                .build();

        // Send notification to the recipients
        Notification notification = ObjectiveStatusChangeNotification.create(
                ObjectiveModelBuilder.build(objective));
        notification.send();

        // Save an event
        FeedEventUtils.create(objective.Id, FeedEventTypes.OBJECTIVE_ACTIVATED);

        return objective;
    }

    /**
     * Given an objective and a user ID, checks whether the objective should be
     * visible to the user.
     */
    @TestVisible
    private static Boolean isVisibleToMe(Objective__c objective, Id viewerUserId) {
        return objective.Status__c == STATUS_DRAFT
                ? objective.CreatedById == viewerUserId
                : true;
    }

    /**
     * Deletes an objective by ID, if it exists.
     */
    public static void deleteObjective(String objectiveId) {
        Objective__c objective = ObjectiveRepository.get(objectiveId);
        if (objective == null) {
            throw new ObjectiveNotFoundException(
                    'Objective not found with objective id: ' + objectiveId);
        }

        ObjectiveRepository.deleteRecord(objective);
    }

    /**
     * Changes the status of an active objective to Closed.
     */
    public static ObjectiveModel closeObjective(String objectiveId) {
        Objective__c objective = ObjectiveRepository.get(objectiveId);
        if (objective == null) {
            throw new ObjectiveNotFoundException(
                    'Objective not found with objective id: ' + objectiveId);
        }

        objective.Closed_Date__c = Datetime.now();
        objective.Status__c = STATUS_CLOSED;
        update objective;

        // Send notification to the recipients
        Notification notification = ObjectiveStatusChangeNotification.create(
                ObjectiveModelBuilder.build(objective));
        notification.send();

        // Save an event
        FeedEventUtils.create(objective.Id, FeedEventTypes.OBJECTIVE_CLOSED);

        return ObjectiveModelBuilder.build(objective);
    }

    /**
     * Builds a SubjectModel representing an objective.
     */
    public static SubjectModel createObjectiveAsSubject(Id objectiveId) {
        Objective__c objective = ObjectiveRepository.get(objectiveId);
        SubjectModel subject = new SubjectModel();
        subject.id = objectiveId;
        subject.name = objective.Title__c;
        subject.tmId = objective.Team_Member__c;
        return subject;
    }

    /**
     * Given an objective ID, gets the ID of its linked conversation (if it exists).
     */
    public static Id getConversationId(Id objectiveId) {
        return getConversationIds(new Set<Id>{objectiveId}).get(objectiveId);
    }

    /**
     * Given some objective IDs, builds a map of their linked conversations in
     * the form Objective ID => Conversation ID.
     */
    public static Map<Id, Id> getConversationIds(Set<Id> objectiveIds) {

        // Find junction objects
        List<Conversation_Subject__c> junctions =
        ConversationSubjectRepository.getSubjectsWithObjectiveIds(objectiveIds);

        // Match objectives to linked conversations
        Map<Id, Id> conversationsByObjectives = new Map<Id, Id>();
        for (Conversation_Subject__c junction : junctions) {
            conversationsByObjectives.put(
                    junction.Objective__c, junction.Conversation__c);
        }
        return conversationsByObjectives;
    }

    /**
     * Gets the URL of a Objective.
     */
    public static String getObjectivePageUrl(Id tmId, Id objectiveId) {
        return fHCM2.UrlHelper.getFullUrl(
                String.format(
                        OBJECTIVES_PAGE,
                        new List<String>{
                                String.valueOf(tmId),
                                String.valueOf(objectiveId)
                        }
                )
        );
    }

    /**
     * Builds a list of Tasks from a list of TaskModels and upserts them.
     */
    public static List<Task__c> buildAndUpsertTasks(
            Id objectiveId, List<TaskModel> taskModels) {

        List<Task__c> tasks = new List<Task__c>();
        Integer index = 0;

        for (TaskModel taskModel : taskModels) {
            Task__c task = new Task__c(
                Id = taskModel.id,
                Objective__c = objectiveId,
                Content__c = taskModel.content,
                Status__c = TaskUtils.getTaskStatus(taskModel),
                Order__c = index
            );
            index++;
            tasks.add(task);
        }

        upsert tasks;
        return tasks;
    }

    /**
     * Deletes any Tasks for an Objective that are missing from the given list.
     */
    public static void deleteMissingTasks(
            Id objectiveId, List<TaskModel> taskModels) {

        // Get IDs from all provided TaskModels
        Set<Id> taskIds = new Set<Id>();
        for (TaskModel taskModel : taskModels) {
            taskIds.add(taskModel.id);
        }

        // Find all missing Tasks
        List<Task__c> tasks =
                TaskRepository.getMissingTasks(objectiveId, taskIds);

        // ... and delete them
        TaskRepository.deleteTasks(tasks);
    }

    /**
     * Finds the Team Members who are the subjects of a list of Objectives.
     */
    public static List<fHCM2__Team_Member__c> getSubjects(List<Objective__c> objectives) {
        Set<Id> subjectIds = new Set<Id>();
        for (Objective__c objective : objectives) {
            subjectIds.add(objective.Team_Member__c);
        }
        return TeamMemberRepository.get(subjectIds);
    }
}