default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{00000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Task__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of task e.g. &#39;active&#39;, &#39;done&#39;</description>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/objectives/builders/TaskModelBuilder.cls
public class TaskModelBuilder {

    public static List<TaskModel> buildTasks(List<Task__c> tasks) {

        List<TaskModel> taskModels = new List<TaskModel>();

        for (Task__c task : tasks) {
            TaskModel taskModel = new TaskModel();
            taskModel.id = task.Id;
            taskModel.content = task.Content__c;
            taskModel.complete = task.Status__c == TaskUtils.STATUS_COMPLETED;
            taskModels.add(taskModel);
        }

        return taskModels;
    }

}