default/objects/Global_Configuration__c/Global_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global configuration options for Performance Management.</description>
    <label>Global Configuration</label>
</CustomObject>

default/objects/Global_Configuration__c/fields/Suppress_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether emails (e.g. for Notifications) are suppressed - used to avoid using up org email allowance during testing.</description>
    <label>Suppress Emails</label>
    <type>Checkbox</type>
</CustomField>

default/classes/common/Notification.cls
/**
 * Class representing a notification about some event.
 */
public virtual class Notification {

    // The contents of this Notification
    public String body { get; set; }

    // The title or subject line of this Notification
    public String title { get; set; }

    // The Ids of TMs who should receive this Notification
    public Set<Id> recipients { get; set; }

    public void send() {
        Global_Configuration__c cfg = ConfigRepository.getGlobalConfig();
        if (cfg.Suppress_Emails__c != true) {
            NotificationUtils.sendEmail(recipients, title, body);
        }
    }
}