default/objects/Global_Configuration__c/Global_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global configuration options for Performance Management.</description>
    <label>Global Configuration</label>
</CustomObject>

default/objects/Global_Configuration__c/fields/Suppress_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether emails (e.g. for Notifications) are suppressed - used to avoid using up org email allowance during testing.</description>
    <label>Suppress Emails</label>
    <type>Checkbox</type>
</CustomField>

default/classes/common/repositories/ConfigRepositoryTest.cls
/**
 * Tests exercising methods dealing with the Global Configuration custom setting.
 */
@isTest
public class ConfigRepositoryTest {

    private static void setSuppression(Boolean suppress) {
        Global_Configuration__c config = new Global_Configuration__c(
            Suppress_Emails__c = suppress
        );
        insert config;
    }

    @isTest
    private static void testGetGlobalConfig() {

        // GIVEN one Global Configuration with Suppress Emails enabled
        setSuppression(true);

        // WHEN I get the most recent Global Config
        Global_Configuration__c config = ConfigRepository.getGlobalConfig();

        // THEN I receive one
        System.assertNotEquals(null, config);

        // AND its Suppress Emails flag is enabled
        System.assertEquals(true, config.Suppress_Emails__c);
    }

}