default/objects/Global_Configuration__c/Global_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global configuration options for Performance Management.</description>
    <label>Global Configuration</label>
</CustomObject>

default/objects/Global_Configuration__c/fields/Aligned_Objectives_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Aligned_Objectives_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether or not Aligned Objectives are enabled across the organisation.</description>
    <inlineHelpText>Whether or not Aligned Objectives are enabled across the organisation.</inlineHelpText>
    <label>Aligned Objectives Enabled</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Global_Configuration__c/fields/Company_Objective_Options__c.field-meta.xml
<CustomField>
    <fullName>Company_Objective_Options__c</fullName>
    <label>Company Objective Options</label>
    <type>TextArea</type>
</CustomField>

default/objects/Global_Configuration__c/fields/Objective_Category_Options__c.field-meta.xml
<CustomField>
    <fullName>Objective_Category_Options__c</fullName>
    <label>Objective Category Options</label>
    <type>TextArea</type>
</CustomField>

default/objects/Global_Configuration__c/fields/Objective_Priority_Options__c.field-meta.xml
<CustomField>
    <fullName>Objective_Priority_Options__c</fullName>
    <label>Objective Priority Options</label>
    <type>TextArea</type>
</CustomField>

default/objects/Global_Configuration__c/fields/Suppress_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether emails (e.g. for Notifications) are suppressed - used to avoid using up org email allowance during testing.</description>
    <label>Suppress Emails</label>
    <type>Checkbox</type>
</CustomField>

default/classes/common/repositories/ConfigRepository.cls
/**
 * Class for handling the Global Configuration custom setting.
 */
public class ConfigRepository {

    /**
     * Gets or creates the singleton Global Configuration instance.
     */
    public static Global_Configuration__c getGlobalConfig() {
        List<Global_Configuration__c> configs = [
            SELECT CreatedDate,
                Aligned_Objectives_Enabled__c,
                Company_Objective_Options__c,
                Objective_Category_Options__c,
                Objective_Priority_Options__c,
                Suppress_Emails__c
            FROM Global_Configuration__c
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        return configs.isEmpty()
                ? new Global_Configuration__c()
                : configs.get(0);
    }

}