default/objects/fHCM2__Policy__c/fields/Conversations_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Conversations_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the Conversations feature is enabled.</description>
    <inlineHelpText>Whether the Conversations feature is enabled.</inlineHelpText>
    <label>Conversations</label>
    <type>Checkbox</type>
</CustomField>

default/objects/fHCM2__Policy__c/fields/Objectives_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Objectives_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the Objectives feature is enabled.</description>
    <inlineHelpText>Whether the Objectives feature is enabled.</inlineHelpText>
    <label>Objectives</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Global_Configuration__c/Global_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global configuration options for Performance Management.</description>
    <label>Global Configuration</label>
</CustomObject>

default/objects/Global_Configuration__c/fields/Company_Objective_Options__c.field-meta.xml
<CustomField>
    <fullName>Company_Objective_Options__c</fullName>
    <label>Company Objective Options</label>
    <type>TextArea</type>
</CustomField>

default/objects/Global_Configuration__c/fields/Objective_Category_Options__c.field-meta.xml
<CustomField>
    <fullName>Objective_Category_Options__c</fullName>
    <label>Objective Category Options</label>
    <type>TextArea</type>
</CustomField>

default/objects/Global_Configuration__c/fields/Objective_Priority_Options__c.field-meta.xml
<CustomField>
    <fullName>Objective_Priority_Options__c</fullName>
    <label>Objective Priority Options</label>
    <type>TextArea</type>
</CustomField>

default/classes/performance/controllers/GlobalConfigController.cls
public class GlobalConfigController {

    public static GlobalConfigResponseModel getGlobalConfig() {

        Global_Configuration__c cfg = ConfigRepository.getGlobalConfig();
        GlobalConfigModel cfgModel = new GlobalConfigModel();

        cfgModel.companyObjectiveOptions =
                createSelectOptions(cfg.Company_Objective_Options__c);

        cfgModel.objectiveCategoryOptions =
                createSelectOptions(cfg.Objective_Category_Options__c);

        cfgModel.objectivePriorityOptions =
                createSelectOptions(cfg.Objective_Priority_Options__c);

        cfgModel.policies = createPolicyModels();

        return new GlobalConfigResponseModel(cfgModel);
    }

    @TestVisible
    private static List<OptionModel> createSelectOptions(String optionsStr) {

        List<OptionModel> options = new List<OptionModel>();

        if (!String.isBlank(optionsStr)) {
            String[] lines = optionsStr.split('\r\n');
            for (String line : lines) {
                options.add(new OptionModel(line, line, false));
            }
        }

        return options;
    }

    @TestVisible
    private static List<PolicyModel> createPolicyModels() {

        Viewport view = new Viewport();

        // Produce a list of all relevant TM IDs
        Set<Id> tmIds = new Set<Id> { view.getViewerTeamMemberId() };
        tmIds.addAll(view.getDirectReportIds());
        
        // Retrieve the Team Members
        List<fHCM2__Team_Member__c> tms = TeamMemberRepository.get(tmIds);

        // Extract the Policy IDs from each Team Member
        Set<Id> policyIds = new Set<Id>();
        for (fHCM2__Team_Member__c tm : tms) {
            policyIds.add(TeamMemberUtils.getPolicyId(tm));
        }

        // Retrieve the Policies
        List<fHCM2__Policy__c> policies = PolicyRepository.get(policyIds);

        // Create a Model for each Policy
        List<PolicyModel> models = new List<PolicyModel>();
        for (fHCM2__Policy__c policy : policies) {
            PolicyModel policyModel = new PolicyModel();
            policyModel.policyId = policy.Id;
            policyModel.conversationsEnabled = policy.Conversations_Is_Active__c;
            policyModel.objectivesEnabled = policy.Objectives_Is_Active__c;
            models.add(policyModel);
        }

        return models;
    }

}